name: Build Action
on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: "24.4.0"
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build action
        run: npm run build

      - name: Build Package
        run: npm run package
